# Generated by Django 4.2.1 on 2023-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
