# Generated by Django 4.2.1 on 2023-06-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0002_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="device",
            name="missed_pings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="missed_pings_threshold",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="session",
            name="device",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="collector.device",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="network",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="collector.network",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="start",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "active session"),
                    ("C", "closed session"),
                    ("F", "closed forcibly session"),
                ],
                default="A",
                max_length=1,
            ),
        ),
    ]
