# Generated by Django 4.2.1 on 2023-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0003_device_last_modified_device_missed_pings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="start",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
