# Generated by Django 4.2.1 on 2023-06-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0004_session_last_modified_alter_session_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="secret_key",
            field=models.CharField(default="", max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="network",
            name="secret_key",
            field=models.CharField(default="", max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
