-- 1. Find the total revenue generated by the restaurant for a specific period of time.

DO $$
DECLARE
    start_date DATE := '2023-01-01';
    end_date DATE := '2023-01-31';
    revenue NUMERIC(10, 2);
BEGIN
    SELECT SUM(order_sum) INTO revenue FROM orders WHERE order_date BETWEEN start_date AND end_date;
    RAISE NOTICE '[% - %] REVENUE: %', start_date, end_date, revenue;
END;
$$;
