--7. Calculate the total revenue generated by each main course.

with basic as (
select mc.main_course_name as main_course_name
, mc.price
, om.portions
, o.order_date
, o.customer_id
, mc.price*om.portions as basic_sum
, dis.percents as perc_meal
, dis."period"
, d2.percents as perc_custom
, d2."period"
, case when dis.period @> o.order_date and dis.meal_id is not null then (mc.price*om.portions * (100 - dis.percents)/100)::numeric(10,2)
       when d2.period @> o.order_date and d2.customer_id  is not null then (mc.price*om.portions * (100 - d2.percents)/100)::numeric(10,2)
       else mc.price*om.portions
       end sum_main_course_disc

FROM meals m
join main_courses mc on mc.id = m.main_course_id
join drinks d on d.id = m.drink_id
join order_meal om on m.id = om.meal_id
join orders o on om.order_id = o.id
join customers c on c.id = o.customer_id
left join discounts dis on dis.meal_id = m.id
left join discounts d2 on d2.customer_id = c.id
order by o.order_date

)

select s.main_course_name,
SUM(s.sum_main_course_disc)
from basic s
group by s.main_course_name
ORDER BY SUM(s.sum_main_course_disc) desc;