# Generated by Django 4.2 on 2023-04-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Units",
            new_name="Unit",
        ),
        migrations.RenameField(
            model_name="set",
            old_name="weight_units",
            new_name="weight_unit",
        ),
    ]
