from faker.providers import DynamicProvider


main_courses_provider = DynamicProvider(
    provider_name="main_course",
    elements=[
        'Chicken with Mashed Potatoes',
        'Beef with Roasted Vegetables',
        'Pork with Steamed Rice',
        'Lamb with Garlic Bread',
        'Fish with Salad',
        'Stir-fry with Noodles',
        'Meatloaf with Green Beans',
        'Pasta with Tomato Sauce',
        'Pulled Pork with Coleslaw',
        'Meatballs with Spaghetti',
        'Roast Beef with Carrots',
        'Grilled Chicken with Asparagus',
        'Pork Chops with Baked Potato',
        'Lamb Chops with Ratatouille',
        'Fish Tacos with Guacamole',
        'Beef Stew with Crusty Bread',
        'Chicken Curry with Rice',
        'Beef Brisket with Cornbread',
        'Pork Tenderloin with Brussels Sprouts',
        'Lamb Shank with Polenta',
        'Grilled Fish with Grilled Vegetables',
        'Sausage with Sauerkraut',
        'Stuffed Peppers with Rice',
        'Meat Pie with Peas',
        'Shepherd Pie with Green Beans',
        'Baked Ziti with Garlic Bread',
        'Beef and Broccoli Stir-fry',
        'Pork Ribs with Baked Beans',
        'Lamb Gyro with Tzatziki Sauce',
        'Fish and Chips with Tartar Sauce',
        'Chicken Alfredo with Broccoli',
        'Beef Tacos with Salsa',
        'Pork Stir-fry with Snow Peas',
        'Lamb Kebabs with Yogurt Sauce',
        'Grilled Salmon with Lemon Butter Sauce',
        'Beef Fajitas with Peppers and Onions',
        'Chicken Fettuccine Alfredo',
        'Pork and Vegetable Stir-fry',
        'Lamb Chops with Mint Sauce',
        'Fish Chowder with Bread Bowl',
        'Beef and Mushroom Stroganoff',
        'Chicken Marsala with Mushrooms',
        'Pork Chops with Applesauce',
        'Lamb Curry with Naan',
        'Tuna Salad with Crackers',
        'Beef Quesadillas with Guacamole',
        'Pork Schnitzel with Potato Salad',
        'Lamb Kabobs with Pita Bread',
        'Grilled Shrimp with Cocktail Sauce',
        'Chicken Enchiladas with Rice',
        'Beef Chili with Cornbread',
        'Pork and Broccoli Stir-fry',
        'Lamb Stew with Bread',
        'Fish Fillet with Lemon Butter Sauce',
        'Roast Chicken with Vegetables',
        'Beef and Vegetable Soup',
        'Pork Loin with Gravy',
        'Lamb Burger with Fries',
        'Grilled Tuna Steak with Salad',
        'Chicken Teriyaki with Broccoli',
        'Beef Pot Roast with Potatoes and Carrots',
        'Pork Roast with Sauerkraut',
        'Lamb Gyro with Feta Cheese',
        'Grilled Swordfish with Vegetables',
        'Chicken Parmesan with Spaghetti',
        'Beef Kebabs with Vegetables',
        'Pork Carnitas with Rice and Beans',
        'Lamb Stew with Dumplings',
        'Fish Soup with Bread',
        'Beef Brisket Sandwich with Coleslaw',
        'Chicken and Dumplings',
        'Pork Chops with Cabbage',
        'Lamb Chops with Roasted Potatoes',
    ],
)
